export type SettingsTab =
  | "Business Info"
  | "Account Settings"
  | "Loyalty Reward"
  | "POS & Printer"
  | "Printer Test"
  | "Kitchen Order"
  | "Table Management"
  | "Tax Settings"
  | "Menu QR Code"
